package in.beze.pilot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusCategoryAllPropertiesEquals(StatusCategory expected, StatusCategory actual) {
        assertStatusCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusCategoryAllUpdatablePropertiesEquals(StatusCategory expected, StatusCategory actual) {
        assertStatusCategoryUpdatableFieldsEquals(expected, actual);
        assertStatusCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusCategoryAutoGeneratedPropertiesEquals(StatusCategory expected, StatusCategory actual) {
        assertThat(expected)
            .as("Verify StatusCategory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusCategoryUpdatableFieldsEquals(StatusCategory expected, StatusCategory actual) {
        assertThat(expected)
            .as("Verify StatusCategory relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusCategoryUpdatableRelationshipsEquals(StatusCategory expected, StatusCategory actual) {
        // empty method
    }
}
